[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pycombustion-solver"
version = "0.1.5"
description = "A 2D reacting flow solver for educational purposes"
readme = "README.md"
requires-python = ">=3.9, <3.12"
license = {text = "Apache-2.0"}
authors = [{name = "HeeSeong. Jung"}]
dependencies = [
    "numpy",
    "numba",
    "matplotlib",
    "pyyaml",
    "tqdm"
]

[project.urls]
"Homepage" = "https://github.com/GreatTOPDuDu/PyCombustion-Solver"
"Bug Tracker" = "https://github.com/GreatTOPDuDu/PyCombustion-Solver/issues"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
[tool.setuptools]
packages = ["CBm0"]



